## Analise multivariada com Regresao Multi-Target - Data Science na Economia

# Projeto: Prevendo Múltiplos Indicadores Macroeconômicos com Regressão Multi-Target

O objetivo é aplicar a técnica de Regressão Multi-Target para prever múltiplos indicadores macroeconômicos simultaneamente. Regressão Multi-Target (ou Regressão Multi-Saída) é uma técnica de aprendizado de máquina para prever mais de uma variável dependente de forma simultânea. Em vez de prever apenas uma variável alvo, como acontece na regressão tradicional, o modelo faz previsões para múltiplas saídas ou alvos ao mesmo tempo.

* O arquivo contém as colunas:

        taxa_juros
        taxa_cambio
        producao_industrial
        pib
        inflacao
        taxa_desemprego
  
>>Os Dados São Ficticios

#### Instalando e Carregando os Pacotes

In [2]:
# Imports

import sklearn
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score

import warnings
warnings.filterwarnings('ignore')

#### Carregando os Dados

In [3]:
df = pd.read_csv('dataset.csv')

In [4]:
df.head()

,taxa_juros,taxa_cambio,producao_industrial,pib,inflacao,taxa_desemprego
0,5.618102,1.740532,89.255853,66.385407,23.102492,33.626470
1,14.260715,3.167604,87.046820,84.632680,30.193113,34.390431
2,10.979909,4.491783,185.938187,131.822108,52.517792,74.375747
3,8.979877,3.928900,87.431930,66.632640,29.988437,33.580560
4,2.340280,4.226245,90.792459,68.815242,26.593498,37.755042

In [5]:
df.shape

(1000, 6)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   taxa_juros           1000 non-null   float64
 1   taxa_cambio          1000 non-null   float64
 2   producao_industrial  1000 non-null   float64
 3   pib                  1000 non-null   float64
 4   inflacao             1000 non-null   float64
 5   taxa_desemprego      1000 non-null   float64
dtypes: float64(6)
memory usage: 47.0 KB

#### Separando Atributos e Targets

In [7]:
# Separando Atributos/Caracteristicas/Variaveis de Entrada e Targets/Variaveis de saida

X = df[['taxa_juros', 'taxa_cambio', 'producao_industrial']]
y = df[['pib', 'inflacao', 'taxa_desemprego']]

In [8]:
# Dividindo os dados em conjuntos de treino e teste

X_treino, X_teste, y_treino, y_teste = train_test_split(X,y, test_size=0.2, random_state=42)

#### Padronização dos Dados

In [9]:
# Padronizando as features

scaler = StandardScaler()
X_treino_scaled = scaler.fit_transform(X_treino)
X_teste_scaled = scaler.transform(X_teste)

#### Construção do Modelo Multi-Target

A Regressão Multi-Target, ou Regressão Multi-Saída, é uma abordagem usada para prever múltiplas variáveis dependentes simultaneamente. Em vez de prever uma única variável de saída, o modelo faz previsões para diversas variáveis de saída. Essa abordagem pode ser vantajosa quando há correlações entre as variáveis de saída, permitindo que o modelo capture essas dependências e forneça previsões mais precisas.

>Existem várias maneiras de implementar a Regressão Multi-Target:

* **Modelos Independentes:** `Treinar um modelo de regressão separado para cada variável de saída`, **`fazendo uma por vez`**. Isso é simples, mas ignora possíveis correlações entre as variáveis de saída.

* **MultiOutputRegressor:** `Utiliza um modelo de regressão base e estende para múltiplas saídas.` Cada saída é tratada como uma regressão separada, mas o mesmo algoritmo de regressão é usado para todas as saídas. Por exemplo, **`MultiOutputRegressor(RandomForestRegressor(...)).`**

* **Modelos Multivariados:** Alguns algoritmos de regressão são naturalmente capazes de lidar com múltiplas saídas, como `Redes Neurais e alguns métodos de aprendizado profundo`. Esses modelos podem capturar melhor as dependências entre as variáveis de saída. **`É utilizado quando se tem um volume grande de dados.`**

* **Modelos de Regressão Conjunta:** Utilizar uma abordagem que `trata todas as variáveis de saída simultaneamente em um único modelo`. Por exemplo, o algoritmo PLS (Partial Least Squares) `pode ser usado para regressão multi-target.`

#### MultiOutputRegressor

In [10]:
# Construindo e treinando o Modelo

modelo = MultiOutputRegressor(RandomForestRegressor(n_estimators = 100, random_state = 42))

#### Definição do Modelo de Regressão Multi-Saída
O código acima define um modelo de regressão multi-saída usando uma combinação do MultiOutputRegressor e do RandomForestRegressor.

* RandomForestRegressor(n_estimators = 100, random_state = 42): Este é o modelo de regressão base que será utilizado. Ele consiste em uma floresta de 100 árvores de decisão (indicadas por n_estimators = 100). O parâmetro random_state = 42 é usado para garantir a reprodutibilidade dos resultados, fixando a semente do gerador de números aleatórios.

* MultiOutputRegressor(...): Esta classe permite estender um modelo de regressão para lidar com múltiplas variáveis dependentes (multi-saída). Cada saída é tratada como uma regressão separada.

Portanto, é um modelo que utiliza uma floresta aleatória para prever múltiplas variáveis dependentes simultaneamente.

Documentação:
>scikit-learn.org/.../sklearn.multioutput.MultiOutputRegressor.html
>
>scikit-learn.org/.../sklearn.multioutput.RegressorChain.html
>
>scikit-learn.org/.../sklearn.multioutput.MultiOutputClassifier.html

#### treinando e Avaliando o Moelo

                ┌──── modelo 1 ────> PIB
        X ──────┤
                ├──── modelo 2 ────> Inflação
                │
                └──── modelo 3 ────> Desemprego

In [11]:
modelo.fit(X_treino_scaled, y_treino)

MultiOutputRegressor(estimator=RandomForestRegressor(random_state=42))

In [12]:
# Fazendo Previsões

y_pred = modelo.predict(X_teste_scaled)

In [13]:
# Mean Squared Error

mse = mean_squared_error(y_teste, y_pred, multioutput= 'raw_values')
print('O mse de cada variável alvo:', mse)

O mse de cada variável alvo: [38.89973612  4.9492735   1.20627582]

O Mean Squared Error (MSE) é uma métrica de avaliação usada para `medir a diferença entre os valores previstos por um modelo e os valores reais` observados. O MSE calcula a média dos quadrados dos erros, ou seja, a média das diferenças quadradas entre os valores reais e previstos. `Um MSE menor, indica um modelo mais preciso.`

In [14]:
# Coeficiente de determinação r2

r2 = r2_score(y_teste, y_pred, multioutput= "raw_values")
print('O r2 de cada vaiavel alvo:', r2)

O r2 de cada vaiavel alvo: [0.94225804 0.94951379 0.99612059]

**Coeficiente de Determinação (R2)**

O coeficiente de determinação, também conhecido como $R2$, é uma métrica que avalia a proporção da variabilidade da variável dependente que é explicada pelo modelo. Ele é amplamente usado para medir a qualidade do ajuste de modelos de regressão.

**O $R2$ varia entre 0 e 1, onde:**
  
* 0 indica que o modelo não explica nenhuma variabilidade da variável alvo.
* 1 indica que o modelo explica toda a variabilidade da variável alvo.

### Visualizando as Previsões

In [16]:
# Visualizar alguns resultados | comparando os valores reais com os que o modelo previu.

resultados = pd.DataFrame(y_teste, columns=['pib','inflacao','taxa_desemprego'])
resultados[['pib_pred','inflacao_pred','taxa_desemprego_pred']] = y_pred

# resultados = pd.concat([
#     pd.DataFrame(y_teste, columns=['pib','inflacao','taxa_desemprego']),
#     pd.DataFrame(y_pred, columns=['pib_pred','inflacao_pred','taxa_desemprego_pred'])], axis=1)

In [17]:
resultados.head()

,pib,inflacao,taxa_desemprego,pib_pred,inflacao_pred,taxa_desemprego_pred
521,63.014526,26.680746,30.276211,54.654841,25.033001,28.161926
737,101.764482,36.175549,52.482609,96.787103,35.584427,51.893981
740,70.147008,30.863583,40.719110,78.477116,31.736756,41.676005
660,80.842988,33.689196,50.421798,83.755337,34.328005,49.263942
411,64.364788,24.215227,28.111229,73.112515,23.400846,28.860764

# Fim.